version: "3"

services:
  docker-mariaDB:
    container_name: docker-todoDB
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planit_todo
      MYSQL_USER: planit
      MYSQL_PASSWORD: planit1234
    ports:
      - 8003:3306

  docker-spring:
    container_name: docker-todo
    image: dlaudghtn/todo-service:t1
    restart: on-failure
    depends_on:
      - docker-mariaDB
    ports:
      - 9002:9002
